### ISSUE TITLE
bug: error when using automatic language routing with ts-node

### ISSUE THREAD

**Issue by sawa-ko** [sapphiredev/plugins#158]
**Describe the bug**
When I don't specify a manual path to where the translation files are for the i18next plugin, using ts-node gives a path error.

**To Reproduce**

1. Write Client with i18next plugin
2. Do not set the "defaultLanguageDirectory" option of the i18next plugin
3. Run the application with ts-node `(ts-node --files src/main.ts)`

**Expected behavior**
That the application correctly loads all language files.

**Screenshots**
![image](https://user-images.githubusercontent.com/56084970/137573130-cb6da5c0-7c05-4ddb-94a6-b5217ccb4a20.png)

**Additional context**
If the language folder path is set manually, the error disappears.
```ts
{
// client options....
  i18n: {
    defaultLanguageDirectory: join(__dirname, '..', 'languages'),
  }
}
```

**Comment by kaname-png** [comment]
> your commands will be registered.. they won't otherwise

My commands still work even if I still have `dist/main.js` as main in `package.json`.

That's why I thought there would be no problem with the i18next plugin.
