### ISSUE TITLE
bug: unknown routes respond with an 200 status and blank response

### ISSUE THREAD

**Issue by animafps** [sapphiredev/plugins#189]
**Describe the bug**

All routes not defined within a file respond with a 200 status and a blank response

**To Reproduce**

1. Install framework and plugin-api
2. register plugin-api and client in a script
3. run
4. go to <http://localhost:4000/any-route>

**Expected behavior**

Should respond with a 404 status code

**Additional context**

Found that when the `ServerEvents.NoMatch` event is emitted the headers are already sent to the client so the status can not be changed

**Comment by kyranet** [comment]
Oh dear, [our API is a hall of shame](https://www.youtube.com/watch?v=nSKp2StlS6s) now 😨.

I'll investigate it in a few hours if nobody else wants to pick this up.
