### ISSUE TITLE
request: make `plugin-logger`'s core independent from framework

### ISSUE THREAD

**Issue by kyranet** [sapphiredev/plugins#34]
**Is your feature request related to a problem? Please describe.**

Right now, if we want to use `plugin-logger` outside a Discord bot, we need to install `@sapphire/framework`, and with it, also `discord.js` and `@types/ws`.

**Describe the solution you'd like**

Make the logger framework agnostic.

**Describe alternatives you've considered**

Overhauling framework and separate it in different parts, `@sapphire/core` (or `@sapphire/framework` as-is), which contains the framework's core code (also no dependencies but Lexure for argument parsing), and `@sapphire/framework-discord.js`, which depends on `discord.js`.

**Additional context**

N/a.

**Comment by vladfrangu** [comment]
> Overhauling framework and separate it in different parts, `@sapphire/core` (or `@sapphire/framework` as-is), which contains the framework's core code (also no dependencies but Lexure for argument parsing), and `@sapphire/framework-discord.js`, which depends on `discord.js`.

Can't we make lib support be a plugin of sorts, instead of a whole.. "framework oh but with extra things"? 👀

**Comment by Nytelife26** [comment]
@kyranet Would it be prevalent to, much like the `register-discordjs` convenience register for plugin-i18next, use a register for standard features and then maybe a `register-sapphire` which does the same but augments sapphire? That would make the dependencies optional.

**Comment by favna** [comment]
I'm going to close this as not further planned. No need to keep open such an old issue that's never going to be picked up.
