### ISSUE TITLE
bug: requiredClientPermissions set for an individual subcommand doesn't trigger *commandDenied

### ISSUE THREAD

**Issue by jowsey** [sapphiredev/plugins#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When setting `requiredClientPermissions` for an individual subcommand, if it fails it will not trigger *commandDenied listeners, and will instead fail silently resulting in a "The application did not respond" response.

This **will** trigger *commandDenied listeners if the client doesn't have that permission.
```ts
public constructor(context: Subcommand.Context, options: Subcommand.Options) {
  super(context, {
    ...options,
    name: "example",
    description: "An example subcommand",
    requiredClientPermissions: [PermissionsBitField.Flags.ManageMessages],
    subcommands: [
      {
        name: "mysubcommand",
        chatInputRun: "chatInputRun"
      }
    ]
  });
}
```

This **won't** trigger *commandDenied listeners.
```ts
public constructor(context: Subcommand.Context, options: Subcommand.Options) {
  super(context, {
    ...options,
    name: "example",
    description: "An example subcommand",
    subcommands: [
      {
        name: "mysubcommand",
        chatInputRun: "chatInputRun",
        requiredClientPermissions: [PermissionsBitField.Flags.ManageMessages]
      }
    ]
  });
}
```

### Steps To Reproduce

1. Create a set of subcommands and give them individual `requiredClientPermissions` values
2. Try to use them without the client having that permission

### Expected behavior

It should trigger *commandDenied listeners

### Screenshots

Top result when setting overall subcommand permissions, bottom result when setting per-subcommand permissions

![image](https://github.com/sapphiredev/plugins/assets/36897817/3e9bc093-3fac-4f6d-b055-84cbe2011d6f)

### Additional context

```json
"@sapphire/framework": "^4.7.2",
"@sapphire/plugin-subcommands": "^5.0.0",
"@sapphire/utilities": "^3.13.0",
"discord.js": "^14.13.0",
"typescript": "^5.2.2"
```

**Comment by favna** [comment]
Subcommands have their own events that are triggered: `chatInputSubcommandDenied`, and `messageSubcommandDenied`

https://github.com/sapphiredev/plugins/blob/e70f8a83e8a84aa986693c9102a57246ceca8637/packages/subcommands/src/lib/types/Events.ts#L7

**Comment by jowsey** [comment]
Ah got it sorry, didn't see it mentioned on the guide :P (p.s. nuh uh)
