### ISSUE TITLE
request(api): ability to transform index.method.ts (or js) into "/"

### ISSUE THREAD

**Issue by SerenModz21** [sapphiredev/plugins#655]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Now that the API plugin has FS-based routing, it would be great if `index.method.ts` (or js) could be transformed into a `/` route. This is a feature that several meta frameworks support, including [Next.js](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#index-routes), [Nuxt](https://nuxt.com/docs/getting-started/routing), and [Astro](https://docs.astro.build/en/guides/routing/).

For example:
- `routes/index.get.ts` transforms into `GET /`
- `routes/settings/index.get.ts` transforms into `GET /settings`
- `routes/settings/index.patch.ts` transforms into `PATCH /settings`

As shown by the examples, it would come in handy on the `/` route and when you want to group all of a route's methods in a directory, rather than flooding other directories.

### Desired solution

A solution and examples have been provided above.

### Alternatives considered

An alternative would be to name it something else that wouldn't conflict with standard routes. An example of this is how [SvelteKit](https://svelte.dev/docs/kit/routing) does it by prefixing the route with a `+`, though I don't think this approach would suit the way Sapphire names routes.

### Additional context

Right now, we have to manually set the route and methods array and that sorta defeats the purpose of FS-based routing a little bit.

**Comment by kyranet** [comment]
This is an oversight on my part, `index` is supposed to be `/`... whoops!

**Comment by kyranet** [comment]
[`@sapphire/plugin-api@7.0.1`](https://github.com/sapphiredev/plugins/releases/tag/%40sapphire%2Fplugin-api%407.0.1) has been released :)
